source 'https://rubygems.org'

gem 'middleman', '~> 4.2'
gem 'middleman-autoprefixer', '~> 2.7'
gem 'tzinfo-data', platforms: [:mswin, :mingw, :jruby]
gem 'wdm', '~> 0.1', platforms: [:mswin, :mingw]
gem 'middleman-livereload'
gem 'haml'
gem 'scss_lint', require: false
gem 'middleman-deploy', '=2.0.0.pre.alpha'
group :development, :test do
  gem 'rspec'
  gem 'capybara'
  gem 'pry-byebug'
end
